name: 'medallion_demo'
version: '1.0.0'

profile: 'medallion_demo'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  medallion_demo:
    # Bronze layer - raw data
    bronze:
      +materialized: view
      +schema: bronze
    # Silver layer - cleaned and conformed data
    silver:
      +materialized: view
      +schema: silver
    # Gold layer - business-level aggregates
    gold:
      +materialized: table
      +schema: gold

seeds:
  +schema: raw_data

vars:
  # Data generation parameters
  num_customers: 100
  num_orders: 500
  num_products: 20
